# 异步任务的超时机制
## 1 多线程实现超时并打断的方式
- 使用`Join(TimeSpan timeout)`方法，传入超时时间并阻塞等待，超时则调用`Interrupt()`打断线程
```cs
/*
 * 本项目用于演示多线程任务如何超时打断
 */
Thread thread = new(Foo);
thread.Start();

//当线程在两秒内完成则返回 true，否则返回 false
if (!thread.Join(TimeSpan.FromSeconds(2)))
{
    //超过两秒，打断线程
    thread.Interrupt();
}

void Foo()
{
    try
    {
        Console.WriteLine("Foo start...");
        Thread.Sleep(5000);
        Console.WriteLine("Foo end...");
    }catch(ThreadInterruptedException)
    {
        Console.WriteLine("Thread is Interrupted...");
    }
    
}
```
## 2 异步任务实现超时并取消的三种方式 
### 2.1 Task.WhenAny()
1. 使用 Task.WhenAny() 传入两个任务，第一个任务是原异步任务，第二个是等待任务(设定几秒超时就等待几秒)
2. 因为 Task.WhenAny() 会返回最先等待到的那个任务，因此若拿到的不是原异步任务，则证明其已超时
```cs
CancellationTokenSource cts = new();
Task fooTask = FooAsync(cts.Token);

/* 这里传入两个 Task，当任一个 Task 结束时就停止等待
 * fooTask 需要 5 秒完成，但 Task.Delay(2000) 只需要 2 秒就能完成
 * 因此这里返回的结果不是 fooTask
 */
Task completedTask = await Task.WhenAny(fooTask, Task.Delay(2000));
if(completedTask != fooTask)    //返回的不是 fooTask，证明它超时了
{
    //fooTask超时，取消掉
    cts.Cancel();
    await fooTask;  //如果没有这一句就不会输出 catch 里面的语句
    Console.WriteLine("Timeout...");
}

Console.WriteLine("Done...");

async Task FooAsync(CancellationToken token)
{
    try
    {
        Console.WriteLine("Foo start...");
        await Task.Delay(5000, token);
        Console.WriteLine("Foo end...");
    }
    catch (OperationCanceledException)
    {
        Console.WriteLine("Foo is Canceled...");
    }
    finally
    {
        cts.Dispose();
    }
}
```

### 2.2 用扩展方法包装 Task.WhenAny()
- 原理与直接用`Task.WhenAny()`相同，但更模块化和简洁
```cs
try
{
    //直接使用扩展语法写即可，两秒未完成则超时取消任务
    await FooAsync(CancellationToken.None).TimeoutAfter(TimeSpan.FromSeconds(2));
    Console.WriteLine("Success!");
}
catch (TimeoutException)
{
    Console.WriteLine("Timeout!");
}

Console.WriteLine("Done...");

async Task FooAsync(CancellationToken token)
{
    try
    {
        Console.WriteLine("Foo start...");
        await Task.Delay(5000, token);
        Console.WriteLine("Foo end...");
    }
    catch (OperationCanceledException)
    {
        Console.WriteLine("Foo is Canceled...");
    }
}

/*
 * 采用扩展方式
 * 代码更模块化，更简洁
 * 仍存在的问题：方法内的 task 没有 Cancel 掉
 */
static class AsyncExtensions
{
    //传入一个任务和一个时间，如果任务时未完成则取消掉
    public static async Task TimeoutAfter(this Task task, TimeSpan timeout)
    {
        //内部维护一个 CancellationTokenSource
        using CancellationTokenSource cts = new();
        Task completedTask = await Task.WhenAny(task, Task.Delay(timeout, cts.Token));
        if (completedTask != task)
        {
            cts.Cancel();
            throw new TimeoutException();
        }

        await task;
    }

    //含返回值的泛型写法
    /*public static async Task<TResult> TimeoutAfter<TResult>(this Task<TResult> task, TimeSpan timeout)
    {
        using CancellationTokenSource cts = new();
        Task completedTask = await Task.WhenAny(task, Task.Delay(timeout, cts.Token));
        if (completedTask != task)
        {
            cts.Cancel();
            throw new TimeoutException();
        }

        return await task;
    }*/
}
```

### 2.2 WaitAsync() 扩展方法
- 使用.Net 6.0 新增的`WaitAsync()`扩展方法
  1. 异步任务后面跟上 WaitAsync() 扩展方法，并传入超时时间
  2. 检测到超时后 WaitAsync() 会直接抛出 TimeoutException 异常
  3. 捕获异常后取消任务即可
```cs
CancellationTokenSource cts = new();
try
{
    /* .Net 6.0 新增的 WaitAsync() 扩展方法，其不含返回值(是这个方法无返回值，不是说使用了这个方法后原异步任务的返回值也没了)
     * WaitAsync() 不像之前的 WhenAny()，需要拿到先返回的那个 completeTask，再判断、再取消
     * 而是会直接抛出 TimeoutException 异常，因此在 catch 语句中取消任务即可
     */
    await FooAsync(cts.Token).WaitAsync(TimeSpan.FromSeconds(2));
    Console.WriteLine("Success!");
}
catch (TimeoutException)
{
    //WaitAsync() 若检测到任务超时，则直接抛出异常，在这里取消任务即可
    cts.Cancel();
    Console.WriteLine("Timeout!");
}
finally
{
    cts.Dispose();
}

Console.WriteLine("Done...");

async Task FooAsync(CancellationToken token)
{
    try
    {
        Console.WriteLine("Foo start...");
        await Task.Delay(5000, token);
        Console.WriteLine("Foo end...");
    }
    catch (OperationCanceledException)
    {
        Console.WriteLine("Foo is Canceled...");
    }
}
```
### 2.x 其他
- 在创建`CancellationTokenSource`时直接传入一个`TimeSpan`，时间到后会自动取消任务
- 但是！这种方法抛出的是`TaskCanceledException`，而不是`TimeoutException`，因此会将*因其他情况而取消*与*因超时而取消*混淆，所以不推荐使用